# Generated by Django 5.2.4 on 2025-08-15 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_profile_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('bills', 'Bills'), ('wants', 'Wants'), ('needs', 'Needs'), ('grocery', 'Grocery'), ('school', 'School/Education'), ('allowance', 'Daily Allowance'), ('load', 'Mobile Load'), ('transportation', 'Transportation'), ('food', 'Food & Dining'), ('entertainment', 'Entertainment'), ('health', 'Health & Medical'), ('clothing', 'Clothing'), ('savings', 'Savings'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Allowances',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
