# Generated by Django 5.2.4 on 2025-08-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_category_type_allowance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allowance',
        ),
    ]
